#!/bin/bash

WEBLOG=$1

# implementation
gawk '{print $1}' "$WEBLOG"|# print out only column 1 of each record
sort |# make identical ip addrs contiguous in output
uniq -c |# for each group of contiguous ip addrs, print single instance plus count
sort -nr |# numerically sort (-n). default is ascending order. (-r) reverses that
head


